version: "3.9"

services:

  postgres:
    image: docker.io/postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "person_db"]
    environment:
      - POSTGRES_PASSWORD=secured-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=person_db

  redis:
    image: docker.io/redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_ARGS="--requirepass secured-redis"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data:
